### ISSUE TITLE
cant open menu - ubuntu 17.04 on notebook

### ISSUE THREAD

**Issue by daniel11609** [nullifiedcat/cathook#104]
Not sure if its the right place to ask...
The discord also seems to be down/invalid....

I need help with opening the menu. Im on a notebook and I have the insert key but its just not working. Cathook is injected properly so what else can I do?

kind regards
Daniel

**Comment by nullifiedcat** [comment]
first, you can do `BindToggle <key> cat_gui_visible`. Second, I'm gonna add F12 key as a secondary gui open key now.

**Comment by daniel11609** [comment]
That's Exactly what I needed!  Maybe if you put that on Readme so other users can just bind it to whatever they like? 
And does the discord still exist because I can't join it says invite  invite

**Comment by nullifiedcat** [comment]
Discord server is being reworked by new admin

**Comment by julianacat** [comment]
https://discord.gg/kvNVNSX

**Comment by daniel11609** [comment]
Bit off topic but what's the cheapest way to play competetive? Phone number is no problem just that I can't really use market and stuff. So I'd have to spent 1$ on in app purchase?

**Comment by nullifiedcat** [comment]
Yes.

**Comment by daniel11609** [comment]
One dollar for a fucking 1 scrap gun I'll just buy key instead and trade it or stuff
