### ISSUE TITLE
Resolving angles freezes game

### ISSUE THREAD

**Issue by aidenx** [nullifiedcat/cathook#107]
If you try to turn on the resolve angles option, the game freezes.

No clue why, it only started happening after the newest update.

**Comment by nullifiedcat** [comment]
Doesn't for me? Tried to reproduce.

**Comment by aidenx** [comment]
That's strange, but okay, must just be an issue for me.

**Comment by julianacat** [comment]
It happened once for me as well :thinking:

**Comment by aabnn** [comment]
same crashes for me

**Comment by nullifiedcat** [comment]
:thinking:

**Comment by CathookRobbie** [comment]
me too ;-;

**Comment by nullifiedcat** [comment]
Reopen it if it still happens after update.
