### ISSUE TITLE
"Wait for sniper rifle charge" does not account for darwin danger shield bullet damage reduction

### ISSUE THREAD

**Issue by snipermain** [nullifiedcat/cathook#111]
It seems to just match the 150 potential damage with the snipper rifle with the sniper's 150 health. Instead, it only does 143 damage. This bug probably exists with other damage reducing items however I am not aware if any others exist.

**Comment by nullifiedcat** [comment]
cloak, passive vaccinator, probably something else

**Comment by SylveonBottle** [comment]
Added sometime in the past week?

https://github.com/nullifiedcat/cathook/blob/79115daf2840674d99a65fbd69ffc282e38c533f/src/hacks/Aimbot.cpp#L367
https://github.com/nullifiedcat/cathook/blob/79115daf2840674d99a65fbd69ffc282e38c533f/src/hacks/Aimbot.cpp#L645

**Comment by julianacat** [comment]
This should be fixed, the function of the second link is just auto-head priority and not the wait for charge. Recently i copied over the code from auto-head and remade the wait for charge with the extra checks like invis and vaccinator.
