### ISSUE TITLE
Anti-Aim doesnt allow free movement

### ISSUE THREAD

**Issue by julianacat** [nullifiedcat/cathook#114]
Changing yaw messes with the way you move

**Comment by nullifiedcat** [comment]
source engine bug I guess? Or probably fix movement function bug.

**Comment by julianacat** [comment]
it was a weird bug where if the aa faced behind you, your wasd movement would be backwards or something. it happened once in a community server, no idea why

**Comment by no-boot-device** [comment]
This is only for when pitch aa is set to HECK on my end.

**Comment by julianacat** [comment]
only breaks with heck aa but thats not an issue
