### ISSUE TITLE
Removecond causes connection to freeze if ping isn't extremely low

### ISSUE THREAD

**Issue by no-boot-device** [nullifiedcat/cathook#119]
This is according to a multitude of reports. 
According to `massive noob#4578` on the discord, it worked for them before commit 022301407b1cdf69d304d04e2a4ee4faaeb4d03c, but I don't know if that's same for everyone.

Steps to reproduce:

1. Join a server with about 100 ping
2. Press removecond key
3. Observe that nothing works anymore

This basically causes removecond to be unusable unless you're really double checking your ping, and completely unusable for people without great connections, which... :finnadie: 
pls fix

**Comment by nullifiedcat** [comment]
I have no idea how to fix that.

**Comment by nullifiedcat** [comment]
If I change command number increment to 300 back, instacap will be unreliable.

**Comment by no-boot-device** [comment]
Perhaps you could have a semi-debug setting for increment as a "workaround"?
Also, the increment might have to be calculated based on ping so that things don't break.

Maybe also try logging messages sent to server, using a server-side plugin instead of from client-side to see if there's anything fishy when freezes happen.

**Comment by nullifiedcat** [comment]
Problem is, I don't have this bug and I can't reproduce it reliably.

**Comment by no-boot-device** [comment]
Go into the community servers listing, sort by latency descending, and pick a server with 150~+ ping, then simply press the removecond key.

**Comment by plasmafart** [comment]
Fake lag breaks it btw

**Comment by SylveonBottle** [comment]
User reported the error was caused due to an update in which the removecond value was (hardcoded) increased by 150. 

Due to the addition of cat_removecond_value, does this mean that the problem fix? Since the user can simply enter a command and fix it themselves, I mean.

**Comment by CathookRobbie** [comment]
basically if the value is 450 it freeze game
but if it's lower than 300, problem fixed.

**Comment by nullifiedcat** [comment]
Fixed.
