### ISSUE TITLE
cat_instant_decloak 1 sometimes freezes spy melee

### ISSUE THREAD

**Issue by SylveonBottle** [nullifiedcat/cathook#131]
This is the stupidist fucking glitch, I've no idea how it even happens. It's 50-50 when it does, but when it does you're fucked. Even if you're in the best spot every to backstab a heavy/demoman/soldier combo on the cart - every last one of them - you just stand there staring at them like a fucking idiot wondering why you can't attack.

Steps:

1. Go spy
2. cat_instant_decloak 1
3. Go invisible
4. Go behind someone
5. Backstab them (doesn't matter if fail)
6. Notice that you can no longer attack (better if you run to test this)

This breaks:

- Spy melee

This doesn't break:

- Spy gun
- Spy sapper
- Spy disguise
- Every other type of attack on every other type of class

My steps to fix this every time it happens:

- Change class
- Attack some
- Change back

**Comment by nullifiedcat** [comment]
check this with new cathook release, reopen if issue still occurs.

**Comment by SylveonBottle** [comment]
For logging purposes, I can confirm that I have not had this issue in over a week now.
