### ISSUE TITLE
[Suggestion] cat_aimbot_keeptarget

### ISSUE THREAD

**Issue by SylveonBottle** [nullifiedcat/cathook#139]
If the aimbot is aiming at someone, don't change the locked player unless they die or go behind a wall.

This will keep smooth_aim + priority from switching between two targets constantly because they:
(depending on what your aimbot priority is set to)
distance: move back and forth from one another
health: someone else looses some health
smart: someone comes in and out of view constantly.

With cat_aimbot_keeptarget, users (I) wouldn't have slowaim problems where it constantly switches between a sniper who's aiming at you while cornering and a random demoman who's afk

**Comment by julianacat** [comment]
target lock has been added in #161

**Comment by Retarded-Skid** [comment]
Could `CachedEntity* target` in `src/hacks/Aimbot.cpp` be used to do a smooth aim silently? Before you have said silent breaks slow aim, but I'd imagine that this could make that a thing of the past. 

Also if you end up doing this, there should be a distinction between *"you are aiming at this guy"* and *"you are aiming at this guy but slow-aim has not ensured you'll headsthot/bodyshot him yet"*.
