### ISSUE TITLE
[Suggestion] Hard-coded Encrypted chat

### ISSUE THREAD

**Issue by SylveonBottle** [nullifiedcat/cathook#141]
Hardcode (can't be disabled) encrypted chat to communicate between cathook users.

Example method of encrypting your message would be to start the message with !!
Have cathook encrypt the rest of the message _in any way_.
In the chat, decrypt the messages if they start with !!

If you're unable to replace user messages with the decrypted version, have cathook make a new chat (-line) with the decrypted message.

Example would be:
`say !!cathook was here`
SylveonBottle: !!Woo7/7RImfOTPmFIPDeaWadWXYJ+pUrW
[Cathook] ^ cathook was here
Onee-chan: !!G+HM/+/8/WkhMCFWu0FCS9Fk/zwbITE2MCEFPuYz
[Cathook] ^ test test testerino

User chat is Username: Message
Cathook decryption would be [Cathook] ^
This is all an example, of course. You could try decrypting the chat directly in the messages, or print decrypted message in console, or whatever you know.

**Comment by no-boot-device** [comment]
but why

**Comment by nullifiedcat** [comment]
My idea:
When sending a message like `!!<data>`, `<data>` gets encrypted using some algorithm `<encdata>`, then, it gets encoded to base64 `<b64encdata>` (so tf2 chat doesn't strip invalid range characters). a checksum (fixed size, 2 characters for example) is appended after it, so `!!<b64encdata><checksum>` is sent to chat.
when receiving data, checksum (last 2 chars) is being used to check if `<b64encdata>` is actually data and not just gibberish. Then, `<b64encdata>` gets decoded from base64 and decrypted using the same algorithm that was used for encrypting it. That message is sent to chat after that.

**Example**: *(encryption not applied, checksum is fake)*
(me) ] `say !!testing`
(legit player's chat):
`nullifiedcat: dGVzdGluZw==4z`
(other cathook user's chat):
(colored) `[e] ` (other color) `nullifiedcat: ` (white) `testing`

**Comment by nullifiedcat** [comment]
Didn't mean to close.

**Comment by nullifiedcat** [comment]
Done! Update cathook.
