### ISSUE TITLE
Engine prediction crashes on disconnect and breaks BHop

### ISSUE THREAD

**Issue by no-boot-device** [nullifiedcat/cathook#149]
Yes, this is listed in the description for it. It's still awful and terrible. Something that should be a default option that doesn't even need a toggle *crashes the game and breaks features*. **WHY** :rage1:

**Comment by julianacat** [comment]
cat told me to add with a toggle

**Comment by no-boot-device** [comment]
that's not the point though
the point is i want it to just werk

**Comment by julianacat** [comment]
Fixed with #157
