### ISSUE TITLE
Legit projectile prediction-esque display for debug purposes

### ISSUE THREAD

**Issue by no-boot-device** [nullifiedcat/cathook#151]
So, cathook's aimbot misses sometimes.

What would be nice is if there was a display to show where it was trying to shoot to make inspecting aimbot errors easier.

**Comment by SylveonBottle** [comment]
System would also be useful for slowaim=1 silent=1, so you can see where aimbot is aiming without having it move the users's aim.

**Comment by julianacat** [comment]
I think the projectile prediction is nice, but why slow aim. All slow aim does is find the closest route to the target, and devides the distance to it so that it doesnt instantly snap. Im just going to use World to screen for the predicted world vector which has nothing to do with slow aim.

**Comment by SylveonBottle** [comment]
Slow aim with silent makes for a "semi legit" aimbot, and works better when silent is on so it doesn't interfere with who the user is aiming at. The only problem with this is that you don't how slow it's actually aiming unless you turn silent off, and with silent off anyone can just run across your FOV and force you to look away from the other team you're trying to kill.

With silent off, and a simple line that shows you were the aimbot is pointing, you'd be able to see who you're aimbot is aiming for without forcing the view on the user.

Think of it as the answer to people who like silent but need to know where the aimbot is aiming.

**Comment by julianacat** [comment]
silent breaks slowaim tho, slowaim is set to not work is silent is enabled and its even stated in its description

**Comment by julianacat** [comment]
cathook now has this feature in the aimbot debug setting as of #157
