### ISSUE TITLE
ESP will sometimes show players you can't see at random spots on-screen

### ISSUE THREAD

**Issue by no-boot-device** [nullifiedcat/cathook#16]
This appears to occur when a player is non-dormant, but the ESP doesn't check if they're in front of you, causing the worldtoscreen check to fail.

(Frankly, I've been using this bug as a makeshift radar. Something along the lines of this but actually intentional would be nice. Like, maybe an actual radar.)

**Comment by nullifiedcat** [comment]
Yeah I know about that issue but I couldn't find out what is causing it (I'm already checking for WorldToScreen to fail but it doesn't help much)

**Comment by collaborating** [comment]
Try doing hud_reloadscheme

**Comment by no-boot-device** [comment]
@collaborating This is a separate thing from that. Basically while locations will sync up usually, the issue is if someone's offscreen, the text that would be attached to their box may appear on screen.

**Comment by nullifiedcat** [comment]
Closed a long time ago actually.
