### ISSUE TITLE
GUI keybinds not working consistently on Ubuntu

### ISSUE THREAD

**Issue by Retarded-Skid** [nullifiedcat/cathook#163]
Two members of the discord have stated that `F11` and `Insert` don't open the GUI for them despite doing a fresh install of the latest Cathook. Another has stated that it worked for them, then randomly stopped working. 

A tempoary fix would be to create the following binds:

```
bind "ins" "cat_gui_visible 1"
bind "escape" "cat_gui_visible 0"
```

The issue with this fix is that when the GUI is open, no keypress events are run by the game for binds. So that escape bind doesn't work when the GUI is open. You have to `cat_gui_visible 0` in console.

**Comment by nullifiedcat** [comment]
For some reason, @julianacat doesn't have this problem. And I have no idea what causes it. I have it too, though

**Comment by nullifiedcat** [comment]
This should be fixed already. If it isn't you can reopen the issue.
