### ISSUE TITLE
Tracers to players

### ISSUE THREAD

**Issue by nullifiedcat** [nullifiedcat/cathook#174]
Add tracers (lines coming from crosshair to enemy head/origin/body/whatever)

**Comment by SylveonBottle** [comment]
https://youtu.be/WKnRzptRKgQ

**Comment by nullifiedcat** [comment]
lmao yeah something like that

**Comment by SylveonBottle** [comment]
Maybe we can have it from the bottom, too. Doesn't show you people behind you, but having the tracers start from the bottom makes is better in my opinion. Doesn't clutter up the middle of the screen, ya'know?

**Comment by nullifiedcat** [comment]
That would be an option

**Comment by julianacat** [comment]
Added in #200 
cat_esp_tracers 1 for center, 2 for bottom
