### ISSUE TITLE
[Suggestion] Lobby link generation command

### ISSUE THREAD

**Issue by Retarded-Skid** [nullifiedcat/cathook#181]
This was suggested in the discord, but a chat command to create a mvm lobby link would be super useful. All it would do would be a API request to `http://mvmlobby.com/tools.php` and print out the output. It would be even better if it was automatically copied to the clipboard.

Some possible names:

* `cat_lobbygen`
* `cat_createlobbylink`
* `cat_genlink`
* `cat_invite`

**Comment by SylveonBottle** [comment]
I'm for this - would be nice. If this is possible, maybe I should look into other API request-able applications to use for cathok integration. cat_steamrep, anyone?

**Comment by nullifiedcat** [comment]
There is no need for API request, cathook already can convert [L:1:...] to 64-bit lobby ID and join it (command cat_fb_lobby [L:....] iirc)

**Comment by nullifiedcat** [comment]
converting the ID here is the easiest part (just OR a 64-bit constant with 32-bit ID). The hardest part is to extract current lobby id from the game (I haven't found out how to do that with steam api yet)

**Comment by julianacat** [comment]
isnt it possible to read from console?
You could try reading 10 lines or so to find a lobby

**Comment by nullifiedcat** [comment]
that's really stupid way to do it tbh.

**Comment by julianacat** [comment]
its stupid, but it would work. If lobby not found, just tell user to press invite button.

**Comment by BenCat07** [comment]
ded.
