### ISSUE TITLE
cat_autobackstab_trickstab

### ISSUE THREAD

**Issue by SylveonBottle** [nullifiedcat/cathook#186]
Have autobackstab stab targets you're not looking at. Would be very useful for trickstabs.

Was going to also suggest cat_aimbot_melee and recommend to use that system, but I noticed that autobackstab does some magic number shit and am now wondering how possible this would even be with the current code.

An alternative suggested name for this would be cat_autobackstab_fov

**Comment by nullifiedcat** [comment]
Autobackstab is basically a triggerbot. Aiming is not a part of its job. You should use aimbot with it if you want dem trixtabs.

**Comment by julianacat** [comment]
Yea, use aimbot, it auto aims for you, its just not so smart about angles but trickstabs are still possible with it.
