### ISSUE TITLE
cat_aimbot_charge to shoot regardless at 100% charge

### ISSUE THREAD

**Issue by SylveonBottle** [nullifiedcat/cathook#188]
If you're aiming at an enemy and they have over the amount of health required for a 1-hit kill, shoot regardless to lower their health.

Main point of this is for MvM where giant robots normally have around 1,000 to 30,000 HP. A single charge at 100% isn't going to kill the robot, so cat_aimbot_charge won't ever let you shoot at them, even though aimbot is constantly trying to target.

Best workaround for this small MvM problem would to just shoot regardless at 100% charge. 
This would also be useful in case you find any players who know about the healarrow trick.

Machina would finally be useful, too.

**Comment by Blackfire62** [comment]
I mean, this entire formula https://github.com/nullifiedcat/cathook/blob/a6ebaf3446c47fd1e81ba6ce6f759616f99abb61/src/hacks/Aimbot.cpp#L352 is wrong, not just that it doesnt shoot at 150 (full) charge.

**Comment by Retarded-Skid** [comment]
Would this work?

```
// wait_for_charge_bypass is a CatVar I added


if ((bdmg * 3) < (HasDarwins(entity) ? (entity->m_iHealth * 1.15) : entity->m_iHealth)) {
	// If player has charge bypassing fire at 100% charge even if wont kill
	if (!wait_for_charge_bypass ||  (wait_for_charge_bypass && g_pLocalPlayer->flZoomBegin != 1.0f)) {
		return false;
	}
}
```

I'm assuming `flZoomBegin != 1.0f` means full charge, unless what @Blackfire62 said would make it require `1.5f`. I'm not familiar with the tf2 code base so :man_shrugging:

**Comment by SylveonBottle** [comment]
[Added in 61654ba](https://github.com/nullifiedcat/cathook/commit/5ae97a724f77ccca0a5c431f43237bdb0fa61b39#diff-b942feb1cdd00abdfcf42d79a425e2dcR394)
