### ISSUE TITLE
Heal arrows damaging people, fov circle not on crosshair

### ISSUE THREAD

**Issue by TLI1233** [nullifiedcat/cathook#194]
So i have a problem when i turn heal arrows on, sometimes they heal and sometimes they damage, mostly damage so how to make it only heal.Also my fov circle is in the upper left of the crosshair how to make it centered

**Comment by nullifiedcat** [comment]
Can you take a screenshot of fov circle issue? And for heal arrows, I can't reproduce the bug. Heal Arrows work perfectly for me.

**Comment by TLI1233** [comment]
Could you tell me what has to be disabled and what options for Heal Arrows and is tehre a delay on them?
As for the screenshot im on windows currently ill jump to Ubuntu and post a screenshot

**Comment by nullifiedcat** [comment]
You shouldn't use Aimbot with heal arrows. Default settings are fine but you can tune delay/charge if you want. No matter how low delay is, you can only shoot a heal arrow once every ~10 seconds (engine limitation).

**Comment by TLI1233** [comment]
So what do you have on the charge and on the delay?

**Comment by nullifiedcat** [comment]
Default values.

**Comment by TLI1233** [comment]
Oh yeah and one more thing can you make configs so itll save the settings

**Comment by TLI1233** [comment]
Also im new to Linux how to reinject, like after restart of the machine?

**Comment by TLI1233** [comment]
Ok found out how to reinject going to get a screenshot

**Comment by nullifiedcat** [comment]
You can save cathook settings with `cat_save <name>` command then `exec cat_<name>` to load it. <name> is the name of config, for example `rage`

**Comment by TLI1233** [comment]
Screenshot 
![screenshot from 2017-07-17 15-40-30](https://user-images.githubusercontent.com/30230088/28270613-6730522a-6b06-11e7-8a25-143298e4745c.png)

**Comment by TLI1233** [comment]
Here it is

**Comment by nullifiedcat** [comment]
Did you change your resolution after injecting cathook?

**Comment by TLI1233** [comment]
Yeah i did

**Comment by nullifiedcat** [comment]
Here's your problem. Don't do that.

**Comment by TLI1233** [comment]
Also do the person have to be hurt or full hp for heal arrows to work?

**Comment by nullifiedcat** [comment]
no

**Comment by TLI1233** [comment]
I see if it happens again and ill screenshot it

**Comment by TLI1233** [comment]
Ok it works now, thanks!
