### ISSUE TITLE
Heal Arrows delay stuck at 0%

### ISSUE THREAD

**Issue by TLI1233** [nullifiedcat/cathook#199]
Screenshot:
![w](https://user-images.githubusercontent.com/30230088/28322687-08f1efd0-6bd7-11e7-91c0-2a3b3ea02d96.png)

**Comment by TLI1233** [comment]
Edit: Cant even shoot healarrow even with 0 delay. please help.

**Comment by nullifiedcat** [comment]
did you change your timeout/charge settings for heal arrows?

**Comment by TLI1233** [comment]
Yeah even if change to charge 0.10 and delay 0. no heal arrow
Charges fully and doesnt shoot

**Comment by nullifiedcat** [comment]
Don't set delay to 0?

**Comment by TLI1233** [comment]
ok but when i set even to 1 it say charge 0%

**Comment by nullifiedcat** [comment]
What's wrong with using default values?

**Comment by TLI1233** [comment]
wait ill see

**Comment by TLI1233** [comment]
even if i exec cat defaults and check only this nothing still at 0, maybe ill reinstall cathook?

**Comment by nullifiedcat** [comment]
Try restarting tf2

**Comment by TLI1233** [comment]
I;ll reinstall

**Comment by TLI1233** [comment]
I got the error while installing failed to clone uccccp  nos uch file or directory.
WHats uccccp?

**Comment by TLI1233** [comment]
Nullified i think i know whats the problem, system decided lets deletee everything in the home folder, had to restart bcoz else it would delete the whole linux

**Comment by LordApple** [comment]
the best settings is stock and delay on 10 then it works everytime
