### ISSUE TITLE
Priority and Friends mode?

### ISSUE THREAD

**Issue by TLI1233** [nullifiedcat/cathook#205]
Is there and option to have friends and priority in enemies?Cause i always shoot my friend spy to the left of me when using silent aim, also I cant seem to work out why does melee aim exist, and ALSO when i try healing someone and theres 2 people, a spy and a solly for example, and i try healing the solly with heal arrows. It locks onto the spy, i have aimbot turned off even the huntsman shit in aimbot preferences off.

**Comment by nullifiedcat** [comment]
There is a playerlist with "Rage" and "Friend" options...
