### ISSUE TITLE
Cant install cathook,

### ISSUE THREAD

**Issue by TLI1233** [nullifiedcat/cathook#228]
I get those fatal errors during install:
In file included from src/backpacktf.cpp:10:0:
src/https_request.hpp:10:25: fatal error: openssl/ssl.h: No such file or directory
 #include <openssl/ssl.h>
                         ^
compilation terminated.
In file included from src/https_request.cpp:8:0:
src/https_request.hpp:10:25: fatal error: openssl/ssl.h: No such file or directory
 #include <openssl/ssl.h>
And when i try to attach i get those:
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0xf7724c89 in __kernel_vsyscall ()
$1 = (void *) 0x0
$2 = 303579792
$3 = 0x12184290 "/tmp/.gl7wN3Ac: cannot open shared object file: No such file or directory"
rm: cannot remove '/tmp/.gl7wN3Ac': No such file or directory
And no Cathook in TF2
I never got those errors in the past.

**Comment by SnowFez** [comment]
Install "Ubuntu other dependencies installation"

`sudo apt update && sudo apt install git libssl-dev:i386 libc6-dev:i386 gdb libsdl2-dev libglew-dev:i386 libfreetype6-dev:i386 -y `

**Comment by nullifiedcat** [comment]
You need libssl-dev:i386 installed.
