### ISSUE TITLE
[suggestion] Walkbot heal/ammo

### ISSUE THREAD

**Issue by cheddar-cheeze** [nullifiedcat/cathook#229]
Walkbot will follow path to healthpack/ammopack if it is located on a path and is low on ammo or health same thing with supply cabinet

**Comment by SylveonBottle** [comment]
Maybe we could add status effects to the walkbot points. I.e., don't go on this path, but prioritize it if you're low on health/ammo.  @julianacat

**Comment by nullifiedcat** [comment]
I work on walkbot, onee works on followbot.

**Comment by nullifiedcat** [comment]
There are already one-way paths (and path flags, but they aren't used yet)

```
	CF_LOW_HEALTH = (1 << 1),
	CF_LOW_AMMO = (1 << 2)```
