### ISSUE TITLE
Conditions are wrong

### ISSUE THREAD

**Issue by no-boot-device** [nullifiedcat/cathook#24]
Some players will have mannpower rune conditions shown as being on their character for no apparent reason. Spies will "have precision" or "have agility" randomly

**Comment by nullifiedcat** [comment]
couldn't reproduce, but I've had this bug before

**Comment by nullifiedcat** [comment]
when you get this again - do `cat_debug_conditions #` on bugged entity ID and show the output

**Comment by no-boot-device** [comment]
This appears to have fixed itself, so /shrug

**Comment by nullifiedcat** [comment]
I've just removed the powerup esp, that isn't a fix.
