### ISSUE TITLE
Bots can't switch weapons.

### ISSUE THREAD

**Issue by SylveonBottle** [nullifiedcat/cathook#243]
RUNNING THIS WITH `textmode-debug`!

Bot cat_autoexec:
```
cat_ipc_connect
exec cat_medic
```

Bot cat_matchexec:
```
autoteam
join_class medic
```

cat_medic (executed in cat_autoexec)
```
cat_fb_bot "1"
cat_fb_always_medigun "1"
cat_autoheal_enabled "1"
cat_nopush_enabled "1"
```

My matchexec includes `cat_fb_tool follow; cat_fb_follow_me`

Bots can not switch to slot2. `cat_fb_always_medigun` does not work. `cat_ipc_exec_all slot2` does not work.

I believe it's because of the "Welcome.." screen that displays at the beginning of joining a match. I'm able to bypass this manually on host tf2 (me) by press D a few times, but the command for D (`+moveright`) does not skip the "Welcome.." screen via commands, thus I'm unable to get the bots to skip it with any method. Since they're also `-textonly`, I can not select the window and press Continue myself.

In @julianacat's [video](https://youtu.be/kns5-nw7xUg?t=1535), he has an autoexec that contains the following:
```bind e "voicemenu 0 0; bot_fb_tool follow; cat_fb_follow_me; cat_ipc_exec_all voicemenu 0 0"```
Before he pressing E, the bot is using slot1. After, it switches to slot2 and begins to heal him.
This command does not make my bot switch to slot2. 

I've been working on trying to fix this for 3 hours now, no one in the discord seems to be able to help as they all claim to be too inexperienced with cathook IPC server. 

I figured this wouldn't be a problem with @nullifiedcat's catbots since they only use slot1, thus this has gone undetected as a `textmode-debug` problem.

**Comment by nullifiedcat** [comment]
`hud_fastswitch 1`
