### ISSUE TITLE
Make nonecore GUI browsable with keyboard

### ISSUE THREAD

**Issue by no-boot-device** [nullifiedcat/cathook#25]
I'm pretty sure that's the point of the menu being set up like that anyway.
My suggestion is arrow keys go through menus and enter allows you to edit values. (toggles on off switches, lets you type in number values)
I don't have nonecorehack, so I don't know if this is the actual set up, but it'd make sense? :suspect:

**Comment by nullifiedcat** [comment]
probably later.

**Comment by julianacat** [comment]
Cathook now uses imgui #157
