### ISSUE TITLE
Cathook issue

### ISSUE THREAD

**Issue by ZakDZ** [nullifiedcat/cathook#260]
First of all  , i am using linux on windows , its a new feature , am using bash on ubuntu , about gcc6 instalation , itried veryifing , there is an error , and i canceled the downlod after more than half an hour , after it , i downloded cathook , but i canceled after a whiel too , earlier this morning , i finded out that i cant install cathoo k , fatal error : path "cathook" already exist and its not empty , i tried using the injection command but it says no command found.
I am totally new to using linux 
any help would be greatly appreciated

**Comment by SylveonBottle** [comment]
Works as intended, cathook is not for windows.
/s

**Comment by nullifiedcat** [comment]
cathook is not intended to use through WSL.

**Comment by ZakDZ** [comment]
Is there anyway i could use it on windows?

**Comment by nullifiedcat** [comment]
No.

**Comment by ZakDZ** [comment]
*sad*

**Comment by ZakDZ** [comment]
teh spycrabing cheat.....

**Comment by ZakDZ** [comment]
am i able to unistall cathook?

**Comment by cheddar-cheeze** [comment]
Boi just delete the files thats it

**Comment by ZakDZ** [comment]
still says file exist and its not empty , nullifiedcat ?
