### ISSUE TITLE
Player Sightlines

### ISSUE THREAD

**Issue by SylveonBottle** [nullifiedcat/cathook#273]
Sight lines that show where players are looking, drawn from the enemy player's head hitbox (or camera, to be more precise) to which way they're looking at.
If the line hits a wall, let's not let it go through that wall.

Possible settings:
Team: [Enemy/Friendly/Both]
Walls: [Always/Darker/Hidden] // Should we show these lines through other walls? think glow esp. "Darker" would just make that part of the line darker if it's behind a wall
Color: [Team/Distance/Default] // "Distance" would be distance away from looking at you, "Default" would be GUI color
FOV Limit: [0-180] // Only show player sightlines if they're looking X° from you

Some settings per-class:
Snipers: [Always/Zoomed/Hidden]
Heavies: [Always/Spinning/Hidden]
Medic: [Always/Primary Out/Hidden]
All other classes would be [Always/Hidden]

Let's also draw lines for where sentries are looking at, maybe a small line for where teleporters are facing. More on that at #274.

**Comment by oneechanhax** [comment]
I added it with lbox's settings, off, sniper and all
