### ISSUE TITLE
Improve infinite_packs for safety

### ISSUE THREAD

**Issue by SylveonBottle** [nullifiedcat/cathook#277]
Simply check if user is invisible as spy, and not activate infinite_packs if so.

I love using infinite_packs, but I hate it when it makes me decloak and undisguise right next to a sentry or something. 

Also, maybe we can do something about medics. maybe not use infinite_pack if you're a medic with over 25% charge or something idk

**Comment by mrsteyk** [comment]
I think this should be closed since removeconding is dead.

**Comment by BenCat07** [comment]
removeconding was revived, will look into this.

**Comment by SylveonBottle** [comment]
@BenCat07 Actually, would rather lock this. Before the death and revival of removecond/timeshift, infinite_pack used to instantly decloak you as a spy, which was undesirable. 

As of its revival, timeshift no longer instantly decloaks you when duplicating healthpacks. In fact, implementing a fix for this issue would actually raise more problems.
