### ISSUE TITLE
tf/cfg/cat_{classname}.cfg

### ISSUE THREAD

**Issue by SylveonBottle** [nullifiedcat/cathook#278]
Similar to cat_autoexec.cfg (which - like autoexec.cfg - runs what's in it in upon launch).

When switching to the scout class, tf2 runs `exec scout`. To automate the process of switching to class-based cathook settings, I've made my own cat_scout.cfg that I run when switching to scout.
For me, I save time by having `exec cat_scout` in my scout.cfg. While this is fine, it's sorta redundent when not using cathook.

So, why not have cat_scout.cfg run when we switch to scout? And cat_sniper.cfg when we switch to sniper, etc.

A simple way to automate switching between configs, by switching alongside of classes.

**Comment by oneechanhax** [comment]
You could always put the changes in scout.cfg, no need to create a cat_scout.cfg
cat_autoexec and matchexec are there because running autoexec doesnt allow cathook commands to be passed as cathook wont be injected and matchexec is nice too because tf2 doesnt include it.

**Comment by SylveonBottle** [comment]
Just a simple quality-of-life improvement idea to throw out there. If that's your response, I'll just do that then.
