### ISSUE TITLE
arch support

### ISSUE THREAD

**Issue by somedoot** [nullifiedcat/cathook#29]
Is this possible in the near future?

**Comment by cropped** [comment]
It already works on arch

**Comment by MisterFancy** [comment]
could you tell us on how to run it on arch?

**Comment by cropped** [comment]
Edit the makefile and change `g++-6` to `g++` and then run make -j4

**Comment by MisterFancy** [comment]
holy crap that was it? i could of done that if i knew to open the make file and read

**Comment by cropped** [comment]
As far as i can tell that's literally all that's wrong with it, A fix would be to change the line:
`CXX=g++-6`
to
`CXX=$(shell which g++)`.
This should make it compatible with almost all distros.

I'm too lazy to make a pull request so if you wanna do it, go nuts.

**Comment by MisterFancy** [comment]
i just posted on the discord about it, so if cat wakes back up maybe he will see it. and it was dm to him. an ty so much

**Comment by cropped** [comment]
Cool, No problem.
Though I realised that the point of specifically using `g++-6` was to ensure the compiler was up to date, using `CXX=$(shell which g++)` doesn't ensure this as it just prints out the location of the compiler so I'm kinda stuck here.

**Comment by MisterFancy** [comment]
the g++ works just fine anfd CXX=$(shell which g++), and as long as people on arch keep g++ up to date the should be fine
