### ISSUE TITLE
Follow Bots crash, Buggy crumbs, and enhancement suggestion

### ISSUE THREAD

**Issue by BenCat07** [nullifiedcat/cathook#294]
The crash:
if a Follow bot follows a player and that player corsses the same path twice the before the bot reaches it, the bot will crash on touching that location, this should be fixed as it extremly restricts the bots.

Sadly can't grab a backtrace as i can only test this in-game

Buggy Crumbs:
From time to time one Bread Crumb just randomly beams to X:0 Y:0 Z:0 which makes the bot get off the path and loose the Palyer it should follow, shoudl also be fixed it possible.

Enhancement Suggestion:
and i noticed that the fllow bots move waaaaay too slow, and can't keep up with the person they're following (move once every ~2 secs), this should be enhanced since else the bot is not really usable.

**Comment by oneechanhax** [comment]
Can you backtrace the first crash in a local server? make sure you `make clean` and build a debug version first   
For the buggy crumbs, turn on draw crumbs and look at the left info. Give me the info on where in those crumb numbers that it goes to 0   
As for being slow, Idk how its slow, it should move at speed of player if it has crumbs and following player is too far away. Please give more info on this.

**Comment by SylveonBottle** [comment]
Followbots are "slow" because they're forced to follow from a distance. If the bot is following someone slower, the bot will have to stop every so often to let the player make new breadcrumbs for it.
The only solution to this is if we add super AI that predicts where players are going and lets the bot walk ahead of the player it's following.

**Comment by oneechanhax** [comment]
Add prediction to followbot :thinking:     
lower follow distance to 50, see how that works

**Comment by BenCat07** [comment]
yeah, my bad, works now, no more crashes suddenly, the bread crumbs also don't bug around anymore, seems to work fine now
