### ISSUE TITLE
Optimize ESP

### ISSUE THREAD

**Issue by no-boot-device** [nullifiedcat/cathook#3]
Toggling ESP on, even with nothing but health box item ESP gives my framerate an aneurysm. 

Apparently a rewrite is in the works for this sort of issue, but either way I'd like to have this listed in the issues so other people know and can work on fixing it too.

**Comment by xcchax** [comment]
cat_esp_vischeck 0

**Comment by no-boot-device** [comment]
After playing for a bit and toggling it on and off, that cvar does make a difference.

It does not make enough of a difference, however.

There's something in the generic ESP loop causing the slowdown, because having ESP on in of itself causes lag without anything on screen it seems.

**Comment by nullifiedcat** [comment]
It does make a difference in `unstable` branch. In `master` it doesn't because vischecks are done for EVERY player/building entity regardless of cat_esp_vischeck setting in entitycache update loop.

**Comment by nullifiedcat** [comment]
Merged unstable with master, closing the issue.
