### ISSUE TITLE
VAC detected a problem

### ISSUE THREAD

**Issue by mrsteyk** [nullifiedcat/cathook#300]
So nowadays VAC loves to complain about some sort of problem which blocks it. IDK why that happens now, about 20 days ago everything was fine. Injected using `attach` script.
Distro: Arch Linux 64bit.

**Comment by mrsteyk** [comment]
Tried Ubuntu 16.04.3 LTS - same shit

**Comment by StevenPolley** [comment]
I've narrowed things down a bit.  

- Not injection method, I have a working LD_PRELOAD injection method which injects fine, but I still get the VAC message
- Doesn't appear to be signature based, I've XOR'd all the strings and have tried a few different post-compile encoders.
- I've stripped out pretty much all the hacks from cathook and just left in some of the base code and hooks, same thing still get the VAC message

To me this means it's checking for any attached shared object attached to the process or perhaps just the hooks have been detected.  I'm going to give up at this point as I'm not familiar enough with the source engine to be productive at this point.

**Comment by NoireCS** [comment]
I have this issue as well, not just on my main desktop, but also my PC. I was looking around for some fixes, but I couldn't find anything other than "Verify your game cache."

**Comment by hkva** [comment]
Removing "prctl(PR_SET_DUMPABLE,0,42,42,42);" from hack::Initialize() fixed the VAC errors for me

**Comment by mrsteyk** [comment]
thnx for 1337 fix. It works for everyone!
