### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Niqqer** [nullifiedcat/cathook#304]
`mkdir -p bin
make data
make[1]: Entering directory '/home/user/cathook'
./check-data ""/opt/cathook/data""
sending incremental file list
./
menu.json
         10.41K 100%    0.00kB/s    0:00:00 (xfr#1, to-chk=13/15)
fonts/
fonts/opensans.ttf
        224.59K 100%  214.19MB/s    0:00:00 (xfr#2, to-chk=10/15)
fonts/roboto.ttf
        135.82K 100%   64.76MB/s    0:00:00 (xfr#3, to-chk=9/15)
fonts/tf2build.ttf
         57.17K 100%   13.63MB/s    0:00:00 (xfr#4, to-chk=8/15)
fonts/unispace.ttf
         49.98K 100%   11.92MB/s    0:00:00 (xfr#5, to-chk=7/15)
fonts/verasans.ttf
         49.05K 100%   11.69MB/s    0:00:00 (xfr#6, to-chk=6/15)
shaders/
shaders/v2f-c4f.frag
             66 100%   12.89kB/s    0:00:00 (xfr#7, to-chk=5/15)
shaders/v2f-c4f.vert
            241 100%   33.62kB/s    0:00:00 (xfr#8, to-chk=4/15)
shaders/v2f-t2f-c4f.frag
            133 100%   18.55kB/s    0:00:00 (xfr#9, to-chk=3/15)
shaders/v2f-t2f-c4f.vert
            345 100%   48.13kB/s    0:00:00 (xfr#10, to-chk=2/15)
shaders/v3f-t2f-c4f.frag
            316 100%   44.08kB/s    0:00:00 (xfr#11, to-chk=1/15)
shaders/v3f-t2f-c4f.vert
            454 100%   63.34kB/s    0:00:00 (xfr#12, to-chk=0/15)

sent 529.64K bytes  received 263 bytes  1.06M bytes/sec
total size is 528.58K  speedup is 1.00
make[1]: Leaving directory '/home/user/cathook'
make bin/libcathook.so
make[1]: Entering directory '/home/user/cathook'
Compiling src/textfile.cpp
cc1plus: warning: /usr/local/include/freetype2: No such file or directory [-Wmissing-include-dirs]
In file included from src/common.h:43:0,
                 from src/textfile.cpp:10:
src/colors.hpp:37:3: warning: ISO C++ prohibits anonymous structs [-Wpedantic]
   };
   ^
In file included from src/common.h:40:0,
                 from src/textfile.cpp:10:
/home/user/cathook/source-sdk-2013/mp/src/public/studio.h: In member function ‘void thinModelVertices_t::SetBoneWeights(int, const mstudioboneweight_t&)’:
src/aftercheaders.h:5:30: warning: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Wstrict-overflow]
 #define max(a,b)  (((a) > (b)) ? (a) : (b))
                              ^
/home/user/cathook/source-sdk-2013/mp/src/public/studio.h: In member function ‘void thinModelVertices_t::GetBoneWeights(int, mstudioboneweight_t*) const’:
src/aftercheaders.h:5:30: warning: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C2 -+ C1 [-Wstrict-overflow]
 #define max(a,b)  (((a) > (b)) ? (a) : (b))
                              ^
In file included from src/common.h:55:0,
                 from src/textfile.cpp:10:
src/EffectGlow.hpp: In member function ‘virtual void effect_glow::EffectGlow::SetParameters(KeyValues*)’:
src/EffectGlow.hpp:22:48: warning: unused parameter ‘params’ [-Wunused-parameter]
  inline virtual void SetParameters( KeyValues *params ) {};
                                                ^~~~~~
In file included from src/common.h:57:0,
                 from src/textfile.cpp:10:
src/EffectChams.hpp: In member function ‘virtual void effect_chams::EffectChams::SetParameters(KeyValues*)’:
src/EffectChams.hpp:20:48: warning: unused parameter ‘params’ [-Wunused-parameter]
  inline virtual void SetParameters( KeyValues *params ) {};
                                                ^~~~~~
In file included from src/common.h:63:0,
                 from src/textfile.cpp:10:
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::PlatformOffset(uint32_t, uint32_t, uint32_t)’:
src/offsets.hpp:29:22: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
   uint32_t result = -1;
                      ^
src/offsets.hpp:30:10: warning: switch missing default case [-Wswitch-default]
   switch (PLATFORM) {
          ^
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::GetUserCmd()’:
src/offsets.hpp:42:76: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t GetUserCmd() {   return PlatformOffset(8, -1, -1); }
                                                                            ^
src/offsets.hpp:42:76: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::ShouldDraw()’:
src/offsets.hpp:43:78: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t ShouldDraw() {   return PlatformOffset(136, -1, -1); }
                                                                              ^
src/offsets.hpp:43:78: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::DrawModelExecute()’:
src/offsets.hpp:44:82: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t DrawModelExecute() {  return PlatformOffset(19, -1, -1); }
                                                                                  ^
src/offsets.hpp:44:82: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::GetClientName()’:
src/offsets.hpp:45:79: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t GetClientName() {  return PlatformOffset(44, -1, -1); }
                                                                               ^
src/offsets.hpp:45:79: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::ProcessSetConVar()’:
src/offsets.hpp:46:81: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t ProcessSetConVar() {  return PlatformOffset(4, -1, -1); }
                                                                                 ^
src/offsets.hpp:46:81: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::ProcessGetCvarValue()’:
src/offsets.hpp:47:85: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t ProcessGetCvarValue() {  return PlatformOffset(29, -1, -1); }
                                                                                     ^
src/offsets.hpp:47:85: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::GetFriendPersonaName()’:
src/offsets.hpp:48:85: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t GetFriendPersonaName() {  return PlatformOffset(7, -1, -1); }
                                                                                     ^
src/offsets.hpp:48:85: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::CreateMove()’:
src/offsets.hpp:49:77: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t CreateMove() {   return PlatformOffset(22, -1, -1); }
                                                                             ^
src/offsets.hpp:49:77: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::PaintTraverse()’:
src/offsets.hpp:50:79: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t PaintTraverse() {  return PlatformOffset(42, -1, -1); }
                                                                               ^
src/offsets.hpp:50:79: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::OverrideView()’:
src/offsets.hpp:51:79: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t OverrideView() {   return PlatformOffset(17, -1, -1); }
                                                                               ^
src/offsets.hpp:51:79: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::FrameStageNotify()’:
src/offsets.hpp:52:82: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t FrameStageNotify() {  return PlatformOffset(35, -1, -1); }
                                                                                  ^
src/offsets.hpp:52:82: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::DispatchUserMessage()’:
src/offsets.hpp:53:85: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t DispatchUserMessage() {  return PlatformOffset(36, -1, -1); }
                                                                                     ^
src/offsets.hpp:53:85: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::CanPacket()’:
src/offsets.hpp:54:75: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t CanPacket() {  return PlatformOffset(57, -1, -1); }
                                                                           ^
src/offsets.hpp:54:75: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::SendNetMsg()’:
src/offsets.hpp:55:76: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t SendNetMsg() {  return PlatformOffset(41, -1, -1); }
                                                                            ^
src/offsets.hpp:55:76: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::Shutdown()’:
src/offsets.hpp:56:74: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t Shutdown() {  return PlatformOffset(37, -1, -1); }
                                                                          ^
src/offsets.hpp:56:74: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::IN_KeyEvent()’:
src/offsets.hpp:57:77: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t IN_KeyEvent() {  return PlatformOffset(20, -1, -1); }
                                                                             ^
src/offsets.hpp:57:77: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::HandleInputEvent()’:
src/offsets.hpp:58:82: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t HandleInputEvent() {  return PlatformOffset(78, -1, -1); }
                                                                                  ^
src/offsets.hpp:58:82: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::LevelInit()’:
src/offsets.hpp:59:76: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t LevelInit() {   return PlatformOffset(23, -1, -1); }
                                                                            ^
src/offsets.hpp:59:76: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::LevelShutdown()’:
src/offsets.hpp:60:79: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t LevelShutdown() {  return PlatformOffset(24, -1, -1); }
                                                                               ^
src/offsets.hpp:60:79: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::BeginFrame()’:
src/offsets.hpp:61:76: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t BeginFrame() {   return PlatformOffset(5, -1, -1); }
                                                                            ^
src/offsets.hpp:61:76: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::FireGameEvent()’:
src/offsets.hpp:62:78: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t FireGameEvent() {  return PlatformOffset(2, -1, -1); }
                                                                              ^
src/offsets.hpp:62:78: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::lastoutgoingcommand()’:
src/offsets.hpp:64:87: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t lastoutgoingcommand() { return PlatformOffset(19228, -1, -1); }
                                                                                       ^
src/offsets.hpp:64:87: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::m_nOutSequenceNr()’:
src/offsets.hpp:65:80: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t m_nOutSequenceNr() { return PlatformOffset(8, -1, -1); }
                                                                                ^
src/offsets.hpp:65:80: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
src/offsets.hpp: In static member function ‘static constexpr uint32_t offsets::m_NetChannel()’:
src/offsets.hpp:66:78: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
  static constexpr uint32_t m_NetChannel() { return PlatformOffset(196, -1, -1); }
                                                                              ^
src/offsets.hpp:66:78: warning: negative integer implicitly converted to unsigned type [-Wsign-conversion]
In file included from src/common.h:70:0,
                 from src/textfile.cpp:10:
src/angles.hpp: In member function ‘void angles::angle_data_s::push(const Vector&)’:
src/angles.hpp:21:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (++angle_index >= count) {
       ~~~~~~~~~~~~~~^~~~~~~~
src/angles.hpp:21:7: warning: conversion to ‘size_t {aka unsigned int}’ from ‘int’ may change the sign of the result [-Wsign-conversion]
   if (++angle_index >= count) {
       ^~~~~~~~~~~~~
src/angles.hpp:33:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (angle_count < count) {
       ~~~~~~~~~~~~^~~~~~~
src/angles.hpp:33:7: warning: conversion to ‘size_t {aka unsigned int}’ from ‘int’ may change the sign of the result [-Wsign-conversion]
   if (angle_count < count) {
       ^~~~~~~~~~~
src/angles.hpp: In member function ‘float angles::angle_data_s::deviation(int) const’:
src/angles.hpp:42:27: warning: conversion to ‘size_t {aka unsigned int}’ from ‘int’ may change the sign of the result [-Wsign-conversion]
    if (j < 0) j = count + j;
                           ^
src/angles.hpp:42:25: warning: conversion to ‘int’ from ‘size_t {aka unsigned int}’ may change the sign of the result [-Wsign-conversion]
    if (j < 0) j = count + j;
                   ~~~~~~^~~
src/angles.hpp:43:27: warning: conversion to ‘size_t {aka unsigned int}’ from ‘int’ may change the sign of the result [-Wsign-conversion]
    if (k < 0) k = count + k;
                           ^
src/angles.hpp:43:25: warning: conversion to ‘int’ from ‘size_t {aka unsigned int}’ may change the sign of the result [-Wsign-conversion]
    if (k < 0) k = count + k;
                   ~~~~~~^~~
In file included from /home/user/cathook/simple-ipc/src/include/ipcb.hpp:26:0,
                 from src/ipc.h:14,
                 from src/common.h:92,
                 from src/textfile.cpp:10:
/home/user/cathook/simple-ipc/src/include/cmp.hpp: In member function ‘T* CatMemoryPool::real_pointer(void*) const’:
/home/user/cathook/simple-ipc/src/include/cmp.hpp:42:80: warning: use of old-style cast [-Wold-style-cast]
  T* real_pointer(void* pointer) const { return reinterpret_cast<T*>((uintptr_t)base + (uintptr_t)pointer); }
                                                                                ^~~~
/home/user/cathook/simple-ipc/src/include/cmp.hpp:42:98: warning: use of old-style cast [-Wold-style-cast]
  T* real_pointer(void* pointer) const { return reinterpret_cast<T*>((uintptr_t)base + (uintptr_t)pointer); }
                                                                                                  ^~~~~~~
/home/user/cathook/simple-ipc/src/include/cmp.hpp: In member function ‘void* CatMemoryPool::pool_pointer(T*) const’:
/home/user/cathook/simple-ipc/src/include/cmp.hpp:45:67: warning: use of old-style cast [-Wold-style-cast]
  void* pool_pointer(T* pointer) const { return (void*)((uintptr_t)pointer - (uintptr_t)base); }
                                                                   ^~~~~~~
/home/user/cathook/simple-ipc/src/include/cmp.hpp:45:88: warning: use of old-style cast [-Wold-style-cast]
  void* pool_pointer(T* pointer) const { return (void*)((uintptr_t)pointer - (uintptr_t)base); }
                                                                                        ^~~~
/home/user/cathook/simple-ipc/src/include/cmp.hpp:45:92: warning: use of old-style cast [-Wold-style-cast]
  void* pool_pointer(T* pointer) const { return (void*)((uintptr_t)pointer - (uintptr_t)base); }
                                                                                            ^
In file included from src/ipc.h:14:0,
                 from src/common.h:92,
                 from src/textfile.cpp:10:
/home/user/cathook/simple-ipc/src/include/ipcb.hpp: In constructor ‘cat_ipc::Peer<S, U>::Peer(std::string, bool, bool)’:
/home/user/cathook/simple-ipc/src/include/ipcb.hpp:82:81: warning: declaration of ‘process_old_commands’ shadows a member of ‘cat_ipc::Peer<S, U>’ [-Wshadow]
  Peer(std::string name, bool process_old_commands = true, bool manager = false) : name(name), process_old_commands(process_old_commands), is_manager(manager) {}
                                                                                 ^
/home/user/cathook/simple-ipc/src/include/ipcb.hpp:278:35: note: shadowed declaration is here
  bool process_old_commands { true };
                                   ^
/home/user/cathook/simple-ipc/src/include/ipcb.hpp:82:81: warning: declaration of ‘name’ shadows a member of ‘cat_ipc::Peer<S, U>’ [-Wshadow]
  Peer(std::string name, bool process_old_commands = true, bool manager = false) : name(name), process_old_commands(process_old_commands), is_manager(manager) {}
                                                                                 ^
/home/user/cathook/simple-ipc/src/include/ipcb.hpp:277:20: note: shadowed declaration is here
  const std::string name;
                    ^~~~
/home/user/cathook/simple-ipc/src/include/ipcb.hpp: In constructor ‘cat_ipc::Peer<S, U>::MutexLock::MutexLock(cat_ipc::Peer<S, U>*)’:
/home/user/cathook/simple-ipc/src/include/ipcb.hpp:100:27: warning: declaration of ‘parent’ shadows a member of ‘cat_ipc::Peer<S, U>::MutexLock’ [-Wshadow]
   MutexLock(Peer* parent) : parent(parent) { pthread_mutex_lock(&parent->memory->mutex); }
                           ^
/home/user/cathook/simple-ipc/src/include/ipcb.hpp:103:9: note: shadowed declaration is here
   Peer* parent;
         ^~~~~~
/home/user/cathook/simple-ipc/src/include/ipcb.hpp: In member function ‘void cat_ipc::Peer<S, U>::Connect()’:
/home/user/cathook/simple-ipc/src/include/ipcb.hpp:127:102: warning: use of old-style cast [-Wold-style-cast]
   memory = (memory_t*)mmap(0, sizeof(memory_t), PROT_WRITE | PROT_READ | PROT_EXEC, MAP_SHARED, fd, 0);
                                                                                                      ^
/home/user/cathook/simple-ipc/src/include/ipcb.hpp: In member function ‘void cat_ipc::Peer<S, U>::ProcessCommands()’:
/home/userv/cathook/simple-ipc/src/include/ipcb.hpp:236:76: warning: use of old-style cast [-Wold-style-cast]
       callback(cmd, cmd.payload_size ? pool->real_pointer<void>((void*)cmd.payload_offset) : nullptr);
                                                                            ^~~~~~~~~~~~~~
/home/user/cathook/simple-ipc/src/include/ipcb.hpp:239:94: warning: use of old-style cast [-Wold-style-cast]
       callback_map[cmd.cmd_type](cmd, cmd.payload_size ? pool->real_pointer<void>((void*)cmd.payload_offset) : nullptr);
                                                                                              ^~~~~~~~~~~~~~
/home/user/cathook/simple-ipc/src/include/ipcb.hpp: In member function ‘void cat_ipc::Peer<S, U>::SendMessage(const char*, unsigned int, unsigned int, const void*, size_t)’:
/home/user/cathook/simple-ipc/src/include/ipcb.hpp:253:51: warning: use of old-style cast [-Wold-style-cast]
    pool->free(pool->real_pointer<void>((void*)cmd.payload_offset));
                                                   ^~~~~~~~~~~~~~
/home/user/cathook/simple-ipc/src/include/ipcb.hpp:262:70: warning: use of old-style cast [-Wold-style-cast]
    cmd.payload_offset = (unsigned long)pool->pool_pointer<void>(block);
                                                                      ^
Compiling src/segvcatch/segvcatch.cpp
cc1plus: warning: /usr/local/include/freetype2: No such file or directory [-Wmissing-include-dirs]
src/segvcatch/segvcatch.cpp: In function ‘void segvcatch::default_segv()’:
src/segvcatch/segvcatch.cpp:31:6: warning: no previous declaration for ‘void segvcatch::default_segv()’ [-Wmissing-declarations]
 void default_segv()
      ^~~~~~~~~~~~
src/segvcatch/segvcatch.cpp: In function ‘void segvcatch::default_fpe()’:
src/segvcatch/segvcatch.cpp:36:6: warning: no previous declaration for ‘void segvcatch::default_fpe()’ [-Wmissing-declarations]
 void default_fpe()
      ^~~~~~~~~~~
src/segvcatch/segvcatch.cpp: In function ‘void segvcatch::handle_segv()’:
src/segvcatch/segvcatch.cpp:41:6: warning: no previous declaration for ‘void segvcatch::handle_segv()’ [-Wmissing-declarations]
 void handle_segv()
      ^~~~~~~~~~~
src/segvcatch/segvcatch.cpp: In function ‘void segvcatch::handle_fpe()’:
src/segvcatch/segvcatch.cpp:47:6: warning: no previous declaration for ‘void segvcatch::handle_fpe()’ [-Wmissing-declarations]
 void handle_fpe()
      ^~~~~~~~~~
In file included from src/segvcatch/segvcatch.cpp:22:0:
src/segvcatch/segvcatch.cpp: In function ‘void segvcatch::_Jv_catch_fpe(int, segvcatch::siginfo_t*, void*)’:
src/segvcatch/i386-signal.h:30:45: warning: use of old-style cast [-Wold-style-cast]
   struct ucontext *_uc = (struct ucontext *)_p;    \
                                             ^
src/segvcatch/segvcatch.cpp:86:5: note: in expansion of macro ‘HANDLE_DIVIDE_OVERFLOW’
     HANDLE_DIVIDE_OVERFLOW;
     ^~~~~~~~~~~~~~~~~~~~~~
src/segvcatch/i386-signal.h:31:26: error: invalid use of incomplete type ‘struct segvcatch::_Jv_catch_fpe(int, segvcatch::siginfo_t*, void*)::ucontext’
   gregset_t &_gregs = _uc->uc_mcontext.gregs;    \
                          ^
src/segvcatch/segvcatch.cpp:86:5: note: in expansion of macro ‘HANDLE_DIVIDE_OVERFLOW’
     HANDLE_DIVIDE_OVERFLOW;
     ^~~~~~~~~~~~~~~~~~~~~~
src/segvcatch/i386-signal.h:30:10: note: forward declaration of ‘struct segvcatch::_Jv_catch_fpe(int, segvcatch::siginfo_t*, void*)::ucontext’
   struct ucontext *_uc = (struct ucontext *)_p;    \
          ^
src/segvcatch/segvcatch.cpp:86:5: note: in expansion of macro ‘HANDLE_DIVIDE_OVERFLOW’
     HANDLE_DIVIDE_OVERFLOW;
     ^~~~~~~~~~~~~~~~~~~~~~
src/segvcatch/i386-signal.h:32:56: warning: use of old-style cast [-Wold-style-cast]
   unsigned char *_eip = (unsigned char *)_gregs[REG_EIP];  \
                                                        ^
src/segvcatch/segvcatch.cpp:86:5: note: in expansion of macro ‘HANDLE_DIVIDE_OVERFLOW’
     HANDLE_DIVIDE_OVERFLOW;
     ^~~~~~~~~~~~~~~~~~~~~~
src/segvcatch/i386-signal.h:56:33: warning: use of old-style cast [-Wold-style-cast]
      _gregs[REG_EAX] == (greg_t)0x80000000UL;   \
                                 ^
src/segvcatch/segvcatch.cpp:86:5: note: in expansion of macro ‘HANDLE_DIVIDE_OVERFLOW’
     HANDLE_DIVIDE_OVERFLOW;
     ^~~~~~~~~~~~~~~~~~~~~~
src/segvcatch/i386-signal.h:63:11: warning: switch missing default case [-Wswitch-default]
    switch (_modrm >> 6)      \
           ^
src/segvcatch/segvcatch.cpp:86:5: note: in expansion of macro ‘HANDLE_DIVIDE_OVERFLOW’
     HANDLE_DIVIDE_OVERFLOW;
     ^~~~~~~~~~~~~~~~~~~~~~
src/segvcatch/i386-signal.h:85:30: warning: use of old-style cast [-Wold-style-cast]
    _gregs[REG_EIP] = (greg_t)_eip;    \
                              ^
src/segvcatch/segvcatch.cpp:86:5: note: in expansion of macro ‘HANDLE_DIVIDE_OVERFLOW’
     HANDLE_DIVIDE_OVERFLOW;
     ^~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [makefile:186: src/segvcatch/segvcatch.o] Error 1
make[1]: Leaving directory '/home/user/cathook'
make: *** [makefile:145: all] Error 2`

**Comment by mrsteyk** [comment]
Are you sure you did everything right? Never got any problems myself

**Comment by NoireCS** [comment]
Try a fresh reinstall of it, I'm having no issues after I reinstalled.

**Comment by Niqqer** [comment]
Tried a fresh reinstall 3x

**Comment by Niqqer** [comment]
Also probably doesn't make a difference, but I'm on arch.

**Comment by Niqqer** [comment]
Also this is the problem : `src/segvcatch/i386-signal.h:31:26: error: invalid use of incomplete type ‘struct segvcatch::_Jv_catch_fpe(int, segvcatch::siginfo_t, void)::ucontext’
gregset_t &_gregs = _uc->uc_mcontext.gregs; 
^
src/segvcatch/segvcatch.cpp:86:5: note: in expansion of macro ‘HANDLE_DIVIDE_OVERFLOW’
HANDLE_DIVIDE_OVERFLOW`

**Comment by Niqqer** [comment]
I already tried a fresh download

**Comment by Niqqer** [comment]
I tried it on my mums Debian machine and it worked, I'm on Arch. Guess it makes a different, but how and why?

**Comment by mrsteyk** [comment]
oof. i get why now. forgot to tell that its because you have newer gcc on arch and you should change segvcatch.h to include one line about safecall.

**Comment by BenCat07** [comment]
fix above, closing.
