### ISSUE TITLE
Crashing tf2

### ISSUE THREAD

**Issue by mimik224** [nullifiedcat/cathook#306]
Running instances: 7298
Attaching to 7298
Running instances: 7298
Detaching from 7298
not found!
loading /home/pc/cathook/bin/libcathook.so to 7298
[New LWP 7299]
[New LWP 7302]
[New LWP 7303]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0xf76ffc89 in __kernel_vsyscall ()
[New Thread 0xec0c8b40 (LWP 7329)]
$1 = (void *) 0xb156580
$2 = 0
$3 = 0x0
Catchpoint 1 (syscalls 'exit' [1] 'exit_group' [252])
[New Thread 0xf7380b40 (LWP 7339)]
[New Thread 0xe3fa0b40 (LWP 7340)]
[Switching to Thread 0xe3fa0b40 (LWP 7340)]

Thread 7 "threaded-ml" hit Catchpoint 1 (call to syscall exit), 0xf76ffc89 in __kernel_vsyscall ()
#0  0xf76ffc89 in __kernel_vsyscall ()
#1  0xf7657361 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#2  0xf758005e in clone () from /lib/i386-linux-gnu/libc.so.6

**Comment by mrsteyk** [comment]
this looks really strange. need more info

**Comment by BenCat07** [comment]
@mimik224 try attach-backtrace and ctrl + c once nothing prints to terminal anymore

**Comment by BenCat07** [comment]
no answer - no need to keep open
