### ISSUE TITLE
Compiling error on arch

### ISSUE THREAD

**Issue by aris200hr** [nullifiedcat/cathook#310]
mkdir -p bin
make data
make[1]: Entering directory '/home/arisdaking/cathook'
./check-data ""/opt/cathook/data""
sending incremental file list

sent 433 bytes  received 14 bytes  894.00 bytes/sec
total size is 528.58K  speedup is 1,182.50
make[1]: Leaving directory '/home/arisdaking/cathook'
make bin/libcathook.so
make[1]: Entering directory '/home/arisdaking/cathook'
Compiling src/segvcatch/segvcatch.cpp
cc1plus: warning: /usr/local/include/freetype2: No such file or directory [-Wmissing-include-dirs]
src/segvcatch/segvcatch.cpp: In function 'void segvcatch::default_segv()':
src/segvcatch/segvcatch.cpp:31:6: warning: no previous declaration for 'void segvcatch::default_segv()' [-Wmissing-declarations]
 void default_segv()
      ^~~~~~~~~~~~
src/segvcatch/segvcatch.cpp: In function 'void segvcatch::default_fpe()':
src/segvcatch/segvcatch.cpp:36:6: warning: no previous declaration for 'void segvcatch::default_fpe()' [-Wmissing-declarations]
 void default_fpe()
      ^~~~~~~~~~~
src/segvcatch/segvcatch.cpp: In function 'void segvcatch::handle_segv()':
src/segvcatch/segvcatch.cpp:41:6: warning: no previous declaration for 'void segvcatch::handle_segv()' [-Wmissing-declarations]
 void handle_segv()
      ^~~~~~~~~~~
src/segvcatch/segvcatch.cpp: In function 'void segvcatch::handle_fpe()':
src/segvcatch/segvcatch.cpp:47:6: warning: no previous declaration for 'void segvcatch::handle_fpe()' [-Wmissing-declarations]
 void handle_fpe()
      ^~~~~~~~~~
In file included from src/segvcatch/segvcatch.cpp:22:0:
src/segvcatch/segvcatch.cpp: In function 'void segvcatch::_Jv_catch_fpe(int, segvcatch::siginfo_t*, void*)':
src/segvcatch/i386-signal.h:30:45: warning: use of old-style cast [-Wold-style-cast]
   struct ucontext *_uc = (struct ucontext *)_p;    \
                                             ^
src/segvcatch/segvcatch.cpp:86:5: note: in expansion of macro 'HANDLE_DIVIDE_OVERFLOW'
     HANDLE_DIVIDE_OVERFLOW;
     ^~~~~~~~~~~~~~~~~~~~~~
src/segvcatch/i386-signal.h:31:26: error: invalid use of incomplete type 'struct segvcatch::_Jv_catch_fpe(int, segvcatch::siginfo_t*, void*)::ucontext'
   gregset_t &_gregs = _uc->uc_mcontext.gregs;    \
                          ^
src/segvcatch/segvcatch.cpp:86:5: note: in expansion of macro 'HANDLE_DIVIDE_OVERFLOW'
     HANDLE_DIVIDE_OVERFLOW;
     ^~~~~~~~~~~~~~~~~~~~~~
src/segvcatch/i386-signal.h:30:10: note: forward declaration of 'struct segvcatch::_Jv_catch_fpe(int, segvcatch::siginfo_t*, void*)::ucontext'
   struct ucontext *_uc = (struct ucontext *)_p;    \
          ^
src/segvcatch/segvcatch.cpp:86:5: note: in expansion of macro 'HANDLE_DIVIDE_OVERFLOW'
     HANDLE_DIVIDE_OVERFLOW;
     ^~~~~~~~~~~~~~~~~~~~~~
src/segvcatch/i386-signal.h:32:56: warning: use of old-style cast [-Wold-style-cast]
   unsigned char *_eip = (unsigned char *)_gregs[REG_EIP];  \
                                                        ^
src/segvcatch/segvcatch.cpp:86:5: note: in expansion of macro 'HANDLE_DIVIDE_OVERFLOW'
     HANDLE_DIVIDE_OVERFLOW;
     ^~~~~~~~~~~~~~~~~~~~~~
src/segvcatch/i386-signal.h:56:33: warning: use of old-style cast [-Wold-style-cast]
      _gregs[REG_EAX] == (greg_t)0x80000000UL;   \
                                 ^
src/segvcatch/segvcatch.cpp:86:5: note: in expansion of macro 'HANDLE_DIVIDE_OVERFLOW'
     HANDLE_DIVIDE_OVERFLOW;
     ^~~~~~~~~~~~~~~~~~~~~~
src/segvcatch/i386-signal.h:63:11: warning: switch missing default case [-Wswitch-default]
    switch (_modrm >> 6)      \
           ^
src/segvcatch/segvcatch.cpp:86:5: note: in expansion of macro 'HANDLE_DIVIDE_OVERFLOW'
     HANDLE_DIVIDE_OVERFLOW;
     ^~~~~~~~~~~~~~~~~~~~~~
src/segvcatch/i386-signal.h:85:30: warning: use of old-style cast [-Wold-style-cast]
    _gregs[REG_EIP] = (greg_t)_eip;    \
                              ^
src/segvcatch/segvcatch.cpp:86:5: note: in expansion of macro 'HANDLE_DIVIDE_OVERFLOW'
     HANDLE_DIVIDE_OVERFLOW;
     ^~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [makefile:186: src/segvcatch/segvcatch.o] Error 1
make[1]: Leaving directory '/home/arisdaking/cathook'
make: *** [makefile:145: all] Error 2

**Comment by BenCat07** [comment]
update gcc-6 and try again
