### ISSUE TITLE
Crash after inject 

### ISSUE THREAD

**Issue by aris200hr** [nullifiedcat/cathook#311]
Running instances: 5869
Attaching to 5869
Running instances: 5869
Detaching from 5869
not found!
loading /home/arisdaking/cathook/bin/libcathook.so to 5869
[New LWP 5870]
[New LWP 5872]
[New LWP 5873]
[New LWP 5897]
[New LWP 5898]
[New LWP 5899]
[New LWP 5900]
[New LWP 5901]
[New LWP 5902]
[New LWP 5903]
[New LWP 5904]
[New LWP 5905]
[New LWP 5907]
[New LWP 5908]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0xf7fb0db9 in __kernel_vsyscall ()
[New Thread 0xe0bf1b40 (LWP 5943)]
$1 = (void *) 0x561fd8c0
$2 = 0
$3 = 0x0
Catchpoint 1 (syscalls 'exit' [1] 'exit_group' [252])
[New Thread 0xddab1b40 (LWP 5945)]

Thread 1 "hl2_linux" received signal SIGSEGV, Segmentation fault.
0xf7bfb706 in __strlen_sse2_bsf () from /usr/lib32/libc.so.6
#0  0xf7bfb706 in __strlen_sse2_bsf () from /usr/lib32/libc.so.6
#1  0xf7e2798c in get_cie_encoding (cie=cie@entry=0xdc048f19) at /build/gcc/src/gcc/libgcc/unwind-dw2-fde.c:300
#2  0xf7e27e77 in classify_object_over_fdes (ob=ob@entry=0xe12e09e4, this_fde=0xe10c3d48, this_fde@entry=0xe10a14cc) at /build/gcc/src/gcc/libgcc/unwind-dw2-fde.c:656
#3  0xf7e283b9 in init_object (ob=0xe12e09e4) at /build/gcc/src/gcc/libgcc/unwind-dw2-fde.c:777
#4  search_object (ob=ob@entry=0xe12e09e4, pc=pc@entry=0xf7e272be <_Unwind_RaiseException+62>) at /build/gcc/src/gcc/libgcc/unwind-dw2-fde.c:989
#5  0xf7e293cc in _Unwind_Find_registered_FDE (bases=0xffea34d4, pc=0xf7e272be <_Unwind_RaiseException+62>) at /build/gcc/src/gcc/libgcc/unwind-dw2-fde.c:1066
#6  _Unwind_Find_FDE (pc=0xf7e272be <_Unwind_RaiseException+62>, bases=0xffea34d4) at /build/gcc/src/gcc/libgcc/unwind-dw2-fde-dip.c:458
#7  0xf7e25ea2 in uw_frame_state_for (context=context@entry=0xffea3480, fs=fs@entry=0xffea3390) at /build/gcc/src/gcc/libgcc/unwind-dw2.c:1249
#8  0xf7e26e76 in uw_init_context_1 (context=context@entry=0xffea3480, outer_cfa=outer_cfa@entry=0xffea3660, outer_ra=0xf7e9f511 <__cxxabiv1::__cxa_throw(void*, std::type_info*, void (*)(void*))+65>) at /build/gcc/src/gcc/libgcc/unwind-dw2.c:1578
#9  0xf7e272bf in _Unwind_RaiseException (exc=0x48757b50) at /build/gcc/src/gcc/libgcc/unwind.inc:88
#10 0xf7e9f511 in __cxxabiv1::__cxa_throw (obj=0x48757b70, tinfo=0xf7fa3720 <typeinfo for std::runtime_error>, dest=0xf7eb5420 <std::runtime_error::~runtime_error()>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:88
#11 0xe1068c4f in ?? () from /home/arisdaking/cathook/bin/libcathook.so
#12 0xe106ab9a in ?? () from /home/arisdaking/cathook/bin/libcathook.so
#13 0xe106b361 in ?? () from /home/arisdaking/cathook/bin/libcathook.so
#14 0xe106b361 in ?? () from /home/arisdaking/cathook/bin/libcathook.so
#15 0xe106c8df in ?? () from /home/arisdaking/cathook/bin/libcathook.so
#16 0xf4613d68 in ?? () from /home/arisdaking/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#17 0xf4613e82 in ?? () from /home/arisdaking/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#18 0xf4614865 in ?? () from /home/arisdaking/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#19 0xf46b9522 in ?? () from /home/arisdaking/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#20 0xf46d43e7 in ?? () from /home/arisdaking/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#21 0xf46d4746 in ?? () from /home/arisdaking/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#22 0xf46d478d in ?? () from /home/arisdaking/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#23 0xf47c533b in ?? () from /home/arisdaking/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#24 0xf47c0fb0 in ?? () from /home/arisdaking/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#25 0xf47c10dd in ?? () from /home/arisdaking/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#26 0xf482b288 in ?? () from /home/arisdaking/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#27 0xf47c2daf in ?? () from /home/arisdaking/.local/share/Steam/steamapps/common/Team Fortress 2/bin/engine.so
#28 0xf65fb038 in ?? ()
#29 0xf65fb038 in ?? ()
#30 0xf65da7af in ?? ()
#31 0x080487ed in main ()

**Comment by mrsteyk** [comment]
Well... Known issue to me. Just do attach-backtrace then ctrl+c and you are golden!

**Comment by mrsteyk** [comment]
and build should be debug.

**Comment by mrsteyk** [comment]
better solution would be is: do some shit like libdwarf and see where exactly it fails without actually needing the debug build aka windows alike.

**Comment by aris200hr** [comment]
oh okay thanks
