### ISSUE TITLE
TeamMates Buildings Chams

### ISSUE THREAD

**Issue by mrsteyk** [nullifiedcat/cathook#317]
![img](https://cdn.discordapp.com/attachments/381860006880083982/391505076348387328/DOOD.png)

**Comment by BenCat07** [comment]
I need info on how to reproduce this

**Comment by mrsteyk** [comment]
Enable chams. Enable buildings chams. Enable teammates buildings chams. Try to build a sentry. It should work. If not, grab it afterwards.

**Comment by BenCat07** [comment]
Fixed in 9fc2705
