### ISSUE TITLE
Fix the GUI Menu

### ISSUE THREAD

**Issue by BenCat07** [nullifiedcat/cathook#319]
.

**Comment by CatLoafToast** [comment]
so my gui menu doesn't open, any other way to configure the cheats?

**Comment by oneechanhax** [comment]
use cat commands
they are concommands for use in the source console

**Comment by CatLoafToast** [comment]
Is there a complete list anywhere?

**Comment by BenCat07** [comment]
find cat_
In console.

Am 08.01.2018 04:06 schrieb "CatLoafToast" <notifications@github.com>:

**Comment by BenCat07** [comment]
@oneechanhax update accordingly to "in progress" and assign null tro this please. thanks.

**Comment by BenCat07** [comment]
done.
