### ISSUE TITLE
Cathook Fails To Inject

### ISSUE THREAD

**Issue by CatLoafToast** [nullifiedcat/cathook#327]
Os: Ubuntu 16.04 LTS, 64 bit

Clean Debug Build
StackTrace:
sample@inspiron15r:~/cathook$ sudo ./attach-backtrace
[sudo] password for sample: 
Running instances: 1100
Attaching to 1100
Running instances: 1100
Detaching from 1100
not found!
loading /home/sample/cathook/bin/libcathook.so to 1100
[New LWP 1101]
[New LWP 1107]
[New LWP 1108]
[New LWP 1130]
[New LWP 1132]
[New LWP 1165]
[New LWP 1168]
[New LWP 1169]
[New LWP 1172]
[New LWP 1196]
[New LWP 1197]
[New LWP 1198]
[New LWP 1199]
[New LWP 1200]
[New LWP 1201]
[New LWP 1202]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0xf2d75898 in ?? () from /home/sample/.local/share/Steam/steamapps/common/Team Fortress 2/bin/materialsystem.so
$1 = (void *) 0x0
$2 = 1998685840
$3 = 0x77218690 "/home/sample/cathook/bin/libcathook.so: cannot open shared object file: No such file or directory"
Catchpoint 1 (syscalls 'exit' [1] 'exit_group' [252])

Gets stuck on last line.

**Comment by BenCat07** [comment]
Build debug, then attach backtrace

Am 07.01.2018 16:55 schrieb "CatLoafToast" <notifications@github.com>:

**Comment by BenCat07** [comment]
Also, you didn't compile cathook.

Am 07.01.2018 18:17 schrieb "Benjamin Dawkins" <bencat07@gmail.com>:

**Comment by CatLoafToast** [comment]
Okay,
I restarted steam, and killed the terminal, in a new terminal, I execute these commands,
make clean
./build-debug-tf2
./attach-backtrace
this is the result
sample@inspiron15r:~/cathook$ ./attach-backtrace
Running instances: 6647
Attaching to 6647
[sudo] password for sample: 
Running instances: 6647
Detaching from 6647
not found!
loading /home/sample/cathook/bin/libcathook.so to 6647
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No symbol table is loaded.  Use the "file" command.
You can't do that without a process to debug.
No symbol table is loaded.  Use the "file" command.
History has not yet reached $2.
Catchpoint 1 (syscalls 'exit' [1] 'exit_group' [252])
The program is not being run.
No stack.

Tried doing it again but putting the ./build-tf2 before the ./build-debug-tf2 command
same result

unisntalled cathook
reinstalled it, source sdk 2013 was missing,
replaced missing file with source sdk 2013,
updated cathook
repeated eariler commands,
same result

I used the command 
git clone --recursive https://github.com/nullifiedcat/cathook && cd cathook && bash build-tf2
to reinstall cathook, it says it's outdated but it's the best I could do.

**Comment by BenCat07** [comment]
git clone --recursive https://github.com/nullifiedcat/cathook.git


You did not clone recursive. Use the above.

Am 07.01.2018 19:45 schrieb "CatLoafToast" <notifications@github.com>:

**Comment by CatLoafToast** [comment]
Do you not need source sdk?

**Comment by BenCat07** [comment]
Cathook automatically has it, you just need to use the colmand above to get
cathook and not just download it aas a zip, you also need to run
make
And
sudo make install
In the libglez and libxoverlay folders and ignore all errors, then build
cathook.

Am 07.01.2018 20:02 schrieb "CatLoafToast" <notifications@github.com>:

**Comment by CatLoafToast** [comment]
After following your directions I did make and sudo make install in both folders,
then after recompiling cathook this is the message I receive, note compile did work

sample@inspiron15r:~/cathook$ ./attach-backtrace
Running instances: 15953
Attaching to 15953
[sudo] password for sample: 
Running instances: 15953
Detaching from 15953
not found!
loading /home/sample/cathook/bin/libcathook.so to 15953
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No symbol table is loaded.  Use the "file" command.
You can't do that without a process to debug.
No symbol table is loaded.  Use the "file" command.
History has not yet reached $2.
Catchpoint 1 (syscalls 'exit' [1] 'exit_group' [252])
The program is not being run.
No stack.

**Comment by BenCat07** [comment]
Show me the compile log.

Am 07.01.2018 20:26 schrieb "CatLoafToast" <notifications@github.com>:

**Comment by CatLoafToast** [comment]
I think this is the log, Compiler.h

/* Compiler.h -- Compiler ypes
2013-11-12 : Igor Pavlov : Public domain */

#ifndef __7Z_COMPILER_H
#define __7Z_COMPILER_H

#ifdef _MSC_VER

  #ifdef UNDER_CE
    #define RPC_NO_WINDOWS_H
    /* #pragma warning(disable : 4115) // '_RPC_ASYNC_STATE' : named type definition in parentheses */
    #pragma warning(disable : 4201) // nonstandard extension used : nameless struct/union
    #pragma warning(disable : 4214) // nonstandard extension used : bit field types other than int
  #endif

  #if _MSC_VER >= 1300
    #pragma warning(disable : 4996) // This function or variable may be unsafe
  #else
    #pragma warning(disable : 4511) // copy constructor could not be generated
    #pragma warning(disable : 4512) // assignment operator could not be generated
    #pragma warning(disable : 4702) // unreachable code
    #pragma warning(disable : 4710) // not inlined
    #pragma warning(disable : 4786) // identifier was truncated to '255' characters in the debug information
  #endif

#endif

#endif

**Comment by BenCat07** [comment]
No, just do
./build-tf2
And give me the output uploaded to pastebin/all errors


Am 07.01.2018 20:38 schrieb "CatLoafToast" <notifications@github.com>:

**Comment by CatLoafToast** [comment]
Think I did it correctly
https://pastebin.com/0ruWE3qu

**Comment by BenCat07** [comment]
You're trying to attach a cathook from an other account, please download it
in your home dir not someone else's

Am 07.01.2018 21:02 schrieb "CatLoafToast" <notifications@github.com>:

**Comment by CatLoafToast** [comment]
It is my home I just put sample instead of my name at first since I'm super paranoid about putting my real information online, so it is in my account.

**Comment by CatLoafToast** [comment]
never mind i'm stupid I didn't put sudo in front of ./attach

**Comment by CatLoafToast** [comment]
Thanks for your time and help it's working

**Comment by BenCat07** [comment]
Then it should work now

Am 07.01.2018 21:08 schrieb "CatLoafToast" <notifications@github.com>:
