### ISSUE TITLE
How sure are we that valve actually detected cathook?

### ISSUE THREAD

**Issue by F-OS** [nullifiedcat/cathook#364]
Like are there any verifiable bans where this cheat was the only software used? Is there a way to confirm it's actually the cheating software and not a injector like gdb? Just wondering.

**Comment by BenCat07** [comment]
It's not quite, Debug builds with NO_STRIP=1 will end up in a ban due to
certain manual linux vac detection

F-OS <notifications@github.com> schrieb am Mo., 19. März 2018, 20:12:

**Comment by BenCat07** [comment]
GDB is not at fault btw.

Benjamin Dawkins <bencat07@gmail.com> schrieb am Mo., 19. März 2018, 20:18:

**Comment by F-OS** [comment]
So a non-debug build that has been stripped can be considered safe for the time being?

**Comment by BenCat07** [comment]
There are some crashes on non-debug, stripped Debug also work just fine.

F-OS <notifications@github.com> schrieb am Mo., 19. März 2018, 21:12:

**Comment by F-OS** [comment]
Alright, thanks.
