### ISSUE TITLE
Aimbot doesn't autocorrect while player is moving

### ISSUE THREAD

**Issue by no-boot-device** [nullifiedcat/cathook#38]
To be specific, the player using the aimbot. I know this sounds really hard to fix, but honestly it'd make using cathook a lot better as I have to stand completely still while raging or I'll miss half my shots.

(Also, messed up the title by pressing enter too early. Goddamn.)

**Comment by nullifiedcat** [comment]
yeah it can be solved by adding engine prediction like in most cheats but I don't understand how it works yet

**Comment by julianacat** [comment]
working engine prediction was added in #157
