### ISSUE TITLE
crithax

### ISSUE THREAD

**Issue by nanoChelik** [nullifiedcat/cathook#383]
Crit hack doesnt work with direct hit (and sometimes with usual rocket launcher)
Have bucket 1000, Forced crits, and nothing happens, im just shooting like without forced crits, but, sometimes, when i join server im able to shot 1 forced crit and thats it.
Im using debug build without no_strip, and experimental crithack 0, dont hinder gameplay 0.

**Comment by BenCat07** [comment]
server limits crits, no time to next crit because the server forbids you to
crit.

nanoChelik <notifications@github.com> schrieb am So., 15. Apr. 2018, 17:30:

**Comment by nanoChelik** [comment]
I undestend it, but with pipe launcher is yellow(orange?) text 'Next critt will be 1.35734953s', and at this time gun reloads and doenst shoot, and if keeping holding m1 and crit key will be crit shot, but not with dh

**Comment by BenCat07** [comment]
Sigh... server limits you from getting too many crits on the same weapon in
a short amount of time, especially directhot since it has a lower crit
chance.

nanoChelik <notifications@github.com> schrieb am So., 15. Apr. 2018, 18:47:

**Comment by nanoChelik** [comment]
for pipelauncher it allowws for dh doesnt?( i dont thrust

**Comment by BenCat07** [comment]
It works on both. Just said conditions.

nanoChelik <notifications@github.com> schrieb am So., 15. Apr. 2018, 20:11:

**Comment by nanoChelik** [comment]
i tryed to recond it, cuz it looks like i cant explain it by words :D
https://streamable.com/2vmc5

**Comment by BenCat07** [comment]
"server limits you from getting too many crits on the same weapon in a
short amount of time, especially directhit since it has a lower crit
chance."
"server limits you from getting too many crits on the same weapon in a
short amount of time, especially directhit since it has a lower crit
chance."
*"server limits you from getting too many crits on the same weapon in a
short amount of time, especially directhit since it has a lower crit
chance."*

>

**Comment by nanoChelik** [comment]
sad that u dont want to fix it

**Comment by BenCat07** [comment]
Don't you pull the 'you are lazy' card on me and then delete that comment. This is NOT SOMETHING YOU CAN AFFECT FROM THE CLIENT, do you understand nie
