### ISSUE TITLE
"cat_glow_teammates 0" acts as "cat_glow_teammates 1" until the respawn friendly-viewing wallhack is disabled

### ISSUE THREAD

**Issue by snipermain** [nullifiedcat/cathook#48]
this can be confusing when respawning when suddenly instead of just enemies, everyone is lit up for a few seconds.

**Comment by nullifiedcat** [comment]
I don't understand what you meant by that.

**Comment by snipermain** [comment]
here are some screenshots:
here I am about 15 seconds after respawning. glow is working normally, with teammates not lit up, as I have inputted into the cathook config. https://i.imgur.com/hCjky7J.png (teammates is off!)

Now here I am immediately after respawning. Notice the blue text above friendly players - that is the "friendly viewing wallhack" im talking about. This tf2 feature breaks the teammate glow setting - as you can see, with teammate glow off in cathook, they are clearly on. https://i.imgur.com/BBQYi9X.png

When the friendly-viewing wallhack disappears (around 10 seconds after respawning) the teammate glow also disappears, making me believe that the friendly viewing wallhack is the problem.

**Comment by nullifiedcat** [comment]
Yes, tf2's default friendly wallhack can't be turned off.

**Comment by nullifiedcat** [comment]
Fixed in 1c887af6f61ee62124fdd23db94c434ffc37bf2a by making teammate glow fully transparent if teammate glow hack is disabled
