### ISSUE TITLE
The "Spy Alert" text should be larger and more noticable

### ISSUE THREAD

**Issue by snipermain** [nullifiedcat/cathook#49]
In the thick of battle, among all the other text it often goes unnoticed and I end up dying to a backstab. As a suggestion I propose that the text is made much larger (and maybe a noise could be played?) when an incoming spy/backstab warning is triggered.

**Comment by nullifiedcat** [comment]
That's a good suggestion, I'll probably add a playsound command

**Comment by nullifiedcat** [comment]
4c895b2f0edbab20040daea1d07220ca13658f99 fixed
