### ISSUE TITLE
Injecting during Valve logo breaks fonts and aimbot

### ISSUE THREAD

**Issue by no-boot-device** [nullifiedcat/cathook#53]
Happened around the time glow was implemented. 

While this is definitely reproducible, I honestly find it to be a fuckin _mystery_ how this happens. :finnadie:

**Comment by nullifiedcat** [comment]
it was always happening, not after glow was added

**Comment by no-boot-device** [comment]
huh, only happened for me after like apr 10th-ish

**Comment by nullifiedcat** [comment]
I can't fix that because it's not really cathook issue I guess. It's not even an issue. You shouldn't inject before game loads completely.
