### ISSUE TITLE
Make buildings have lesser priority than players

### ISSUE THREAD

**Issue by julianacan9999** [nullifiedcat/cathook#71]
Make aimbot target players first rather than the buildings, usefull for picking that annoying engineer hiding behind his buildings.
Priority list:
Player > Sentry > Other buildings

**Comment by FartOnCats** [comment]
set it to fov, then look at the engi

**Comment by julianacan9999** [comment]
no

**Comment by nullifiedcat** [comment]
isn't it already like that?

**Comment by julianacan9999** [comment]
If you use distance priority and the engineer just sits behind a sentry easily hit able, the aim bot will just target the sentry since its closer. Yes the sentry technically should be shot first by the sentry, but In almost all situations its better to kill the engineer or his teammates rather than the harass sentry
![screenshot_20170422_145631](https://cloud.githubusercontent.com/assets/3690021/25307748/1f70f44a-276c-11e7-8817-cdb9ff2d68a6.png)

**Comment by nullifiedcat** [comment]
weird

**Comment by nullifiedcat** [comment]
Fixed
