### ISSUE TITLE
Follow bot improvements

### ISSUE THREAD

**Issue by julianacat** [nullifiedcat/cathook#75]
1. Bots use a better following system.
Cat stated at some point that this is a possibility to use .nav files but its a really hard feature to make. An alternative is for the bots to draw bread crumbs from the player its supposed to follow and use the bread crumbs as a way of finding and following the player, lmaobox uses this technique. Its nice to keep from having to babysit bots to keep them from getting stuck around corners.
2. Bots focus healing
Bots currently just heal whoever, It would be nice to have the main priority given to the main player its following to keep alive with second priority going to other bots. Having more heals heeps you alive, which inturn keeps your bots alive.
3. Bot selection through gui
Using the newly added player list, you could select and command a bot using it. Nice and easy for bot management for on the fly sharing of bots with lobby members.
4. On death action
Have a command run on your death. Having bots stand in place after your death makes them sitting ducks waiting for death, Having them follow someone else until your arrival can fix this so long as its someone who wont suicide to kill your bots.

**Comment by nullifiedcat** [comment]
AutoHeal actually has priority system, read the source code for it.

**Comment by julianacan9999** [comment]
Then scratch 2. Being able to tweak priorities would be cool but i dont know how usefull that would prove.
