### ISSUE TITLE
Cathook crashes when injecting

### ISSUE THREAD

**Issue by iris1337** [nullifiedcat/cathook#85]
When I try to attach cathook (on the latest version, I did update and recompile it 3 times), it automatically crashes to desktop.

Here's what it outputs when I do attach-backtrace:

> Running instances: 8376
Attaching to 8376
Running instances: 8376
 Detaching from 8376
not found!
loading /home/iris/cathook/bin/libcathook.so to 8376
[New LWP 8377]
[New LWP 8380]
[New LWP 8381]
[New LWP 8389]
[New LWP 8391]
[New LWP 8403]
[New LWP 8404]
[New LWP 8405]
[New LWP 8406]
[New LWP 8413]
[New LWP 8414]
[New LWP 8415]
[New LWP 8416]
[New LWP 8417]
[New LWP 8418]
[New LWP 8431]
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0xf7784c89 in __kernel_vsyscall ()
[New Thread 0xdb5eab40 (LWP 10959)]
$1 = (void *) 0x27e39700
$2 = 0
$3 = 0x0
Catchpoint 1 (syscalls 'exit' [1] 'exit_group' [252])
Thread 18 "hl2_linux" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xdb5eab40 (LWP 10959)]
0xf72094cc in ?? () from /usr/lib32/nvidia-378/libGLdispatch.so.0
#0  0xf72094cc in ?? () from /usr/lib32/nvidia-378/libGLdispatch.so.0
#1  0xf574c66a in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/libtogl.so
#2  0xf576ba1f in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/libtogl.so
#3  0xf57584d8 in IDirect3DDevice9::CreateTexture(unsigned int, unsigned int, unsigned int, unsigned int, _D3DFORMAT, _D3DPOOL, IDirect3DTexture9**, void**, char*) () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/libtogl.so
#4  0xef902a11 in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/shaderapidx9.so
#5  0xef8f6edb in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/shaderapidx9.so
#6  0xf0d64862 in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/materialsystem.so
#7  0xf0d6a37e in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/materialsystem.so
#8  0xf0d6aa21 in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/materialsystem.so
#9  0xf0d6aee3 in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/materialsystem.so
#10 0xf0d8c347 in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/materialsystem.so
#11 0xf0d8e0a2 in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/materialsystem.so
#12 0xf0d23e24 in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/materialsystem.so
#13 0xf0d84907 in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/materialsystem.so
#14 0xeda5443c in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/stdshader_dx9.so
#15 0xeda24a82 in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/stdshader_dx9.so
#16 0xeda1a803 in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/stdshader_dx9.so
#17 0xeda53d8d in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/stdshader_dx9.so
#18 0xf0d86325 in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/materialsystem.so
#19 0xf0d173f6 in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/materialsystem.so
#20 0xf0d16165 in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/materialsystem.so
#21 0xefc57434 in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/vguimatsurface.so
#22 0xefc57b94 in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/vguimatsurface.so
#23 0xefc45317 in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/vguimatsurface.so
#24 0xefc3f0da in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/vguimatsurface.so
#25 0xefc3f12d in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/vguimatsurface.so
#26 0xefc3f32d in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/bin/vguimatsurface.so
#27 0xe5e6c6b4 in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/tf/bin/client.so
#28 0xe5e6c48b in ?? () from /home/iris/.local/share/Steam/steamapps/common/Team Fortress 2/tf/bin/client.so
#29 0xe2b525cd in hack::Initialize () at src/hack.cpp:192
#30 0xe2bb0719 in MainThread (arg=0xe2e766c4 <mutex_quit>) at src/entry.cpp:29
#31 0xf76b8295 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#32 0xf75e0eee in clone () from /lib/i386-linux-gnu/libc.so.6

Only occurs with the latest version, I can run previous versions (such as #FD555D), but not this one.

**Comment by nullifiedcat** [comment]
Hmmm, looks like changing convar outside main thread is a bad idea. Will be fixed!
